In [1]:
import numpy as np
import fisher as f

Test function which adds a priors covariance matrix to our Fisher matrix.

In [2]:
# Set up test data.

folder= '/home/danielle/Documents/CMU/Research/EG_comparison/txtfiles/'

Fisher = np.loadtxt(folder+ '/Fisher_Eg_N=1e5_varall.txt')

f_keys = folder+'/keys_N=1e5_varall.txt'

with open(f_keys) as fi:
    keys_list = fi.readlines()
    
keys_list = [x.strip() for x in keys_list]
print keys_list

['OmB', 'b', 'n_s', 'sigma8', 'h', 'sigma_0', 'OmM', 'mu_0']


In [3]:
# Load a priors matrix from the LCDM case and strip the parameters we don't care about:
priors_cov_full = np.loadtxt('/home/danielle/Documents/CMU/Research/EG_comparison/LCDM_priors/cov_with_om_b.mat')
cut_params = [0,1,2,3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,
             39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,
             72,73,74]

priors_cov = np.delete(np.delete(priors_cov_full, cut_params,axis=0), cut_params, axis=1)

# Switch from H0 to h.
for i in range(len(priors_cov[:,0])):
    for j in range(len(priors_cov[:,0])):
        if i==1:
            priors_cov[i,j] = priors_cov[i,j]/100.
        if j==1:
            priors_cov[i,j] = priors_cov[i,j]/100.

np.savetxt(folder+'/priors_cov_LCDM_test.txt', priors_cov)

In [4]:
priors_file = '/home/danielle/Documents/CMU/Research/EG_comparison/txtfiles/priors_cov_LCDM_test.txt'
keys_priors_file = '/home/danielle/Documents/CMU/Research/EG_comparison/txtfiles/keys_priors_LCDM_test.txt'

In [5]:
Fish_with_priors = f.add_priors(Fisher, keys_list, priors_file, keys_priors_file)

In [6]:
print "Fish_with_priors=", Fish_with_priors

Fish_with_priors= [[ 8.21459704e+06 -2.58621101e-15  5.35542095e+04 -1.37082256e-15  7.81884145e+05 -6.71962789e-01 -3.92390985e+00  1.91584103e-01]
 [-2.58621101e-15  2.32780056e-26  3.74464168e-16  7.03375050e-27 -7.35117907e-15  4.33743076e-12  2.53286557e-11 -1.23668485e-12]
 [ 5.35542095e+04  3.74464168e-16  9.32406503e+04  1.87792909e-16 -4.54150754e+04  9.33412988e-02  5.45066011e-01 -2.66128718e-02]
 [-1.37082256e-15  7.03375050e-27  1.87792909e-16  2.16625891e-26 -2.16158529e-15  1.31542631e-12  7.68147704e-12 -3.75046634e-13]
 [ 7.81884145e+05 -7.35117907e-15 -4.54150754e+04 -2.16158529e-15  1.32942026e+05 -1.56641993e+00 -9.14717171e+00  4.46615313e-01]
 [-6.71962789e-01  4.33743076e-12  9.33412988e-02  1.31542631e-12 -1.56641993e+00  9.33640267e+02  5.45202673e+03 -2.66197844e+02]
 [-3.92390985e+00  2.53286557e-11  5.45066011e-01  7.68147704e-12 -9.14717171e+00  5.45202673e+03  3.18373109e+04 -1.55447212e+03]
 [ 1.91584103e-01 -1.23668485e-12 -2.66128718e-02 -3.75046634e-13